/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 haccpc.gltf --transform
Author: PewPew (https://sketchfab.com/Pew.Pew)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hacker-laptop-803cf6b3a1ac4de9b3306e9c119516c3
Title: Hacker Laptop
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function Model(props) {
  const { nodes, materials } = useGLTF("/haccpc-transformed.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Laptop_laptop_material_0.geometry}
        material={materials.laptop_material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[986.63, 1317.45, 59.35]}
      />
    </group>
  )
}

useGLTF.preload("/haccpc-transformed.glb")
