/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 pixel.gltf --transform
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/commodore-64-0cd1d83a17bf4b9bb318bb49e6df229c
Title: Commodore 64
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function Model(props) {
  const { nodes, materials } = useGLTF("/pixel-transformed.glb")
  return (
    <group {...props} dispose={null}>
      <group
        position={[60.51, 39.28, 60.51]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.Plane001__0.geometry}
            material={materials.Plane001__0}
            position={[0, 90.04, -238.15]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["Box001_02_-_Default_0"].geometry}
            material={materials["02_-_Default"]}
            position={[70.98, 155.11, -1.14]}
            rotation={[0, -0.17, -Math.PI / 2]}
            scale={[1, 1, 1.95]}
          />
          <mesh
            geometry={nodes["Box002_07_-_Default_0"].geometry}
            material={materials["07_-_Default"]}
            position={[120.62, -148.98, 6.55]}
            scale={[1, 1, 0.31]}
          />
          <mesh
            geometry={nodes["musta_base_03_-_Default_0"].geometry}
            material={materials["03_-_Default"]}
            position={[0, 90.04, -238.15]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["musta_nappis_03_-_Default_0"].geometry}
            material={materials["03_-_Default"]}
            position={[70.98, 155.11, -1.14]}
            rotation={[0, -0.17, -Math.PI / 2]}
            scale={[1, 1, 1.95]}
          />
          <mesh
            geometry={nodes["musta_lampu_03_-_Default_0"].geometry}
            material={materials["03_-_Default"]}
            position={[120.62, -148.98, 6.55]}
            scale={[1, 1, 0.31]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/pixel-transformed.glb")
