/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 rak.gltf --transform
Author: katashofi (https://sketchfab.com/katashofi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rak-server-5dff62add9294d9fae66cabd04458a83
Title: Rak Server
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function Model(props) {
  const { nodes, materials } = useGLTF("/rak-transformed.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.root_Material_58_0.geometry}
        material={materials.Material_58}
        position={[0.01, 0.01, 0.2]}
        scale={[0.19, 0.44, 0.22]}
      />
    </group>
  )
}

useGLTF.preload("/rak-transformed.glb")
